version: "3"

services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry
  browser:
    image: klausmeyer/docker-registry-browser
    environment:
      - DOCKER_REGISTRY_URL=http://registry:5000
      - SECRET_KEY_BASE=6db80b9e2036c41f65f46450c37c27f4b04dfb21457b6872745278f66d798848673f6cd7c754ab9e719ea5a72e0dd30de8bce8a28be1f04f9873c95afa6febd0
    ports:
      - 5001:8080

volumes:
  registry:
