services:
  service1:
    image: docker:dind
    privileged: true
    networks:
      mynetwork:
        ipv4_address: 172.116.0.2
    command:
      [
        "dockerd",
        "-H",
        "unix:///var/run/docker.sock",
        "-H",
        "tcp://0.0.0.0:2375",
        "--tls=false"
      ]
    environment:
      - DOCKER_TLS_CERTDIR=
      - DOCKER_HOST=tcp://172.116.0.2:2375
    # Add additional configurations for service1 if needed
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.116.0.0/24
